# Generated by Django 3.1.3 on 2020-11-25 16:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('timestamp', models.DateTimeField()),
                ('supply_id', models.BigIntegerField()),
                ('order_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('status', models.CharField(choices=[('COM', 'CANCELLED'), ('CAN', 'CANCELLED')], max_length=4)),
            ],
            options={
                'verbose_name': 'SupplyOrder',
                'verbose_name_plural': 'SupplyOrders',
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='supplyorder',
            index=models.Index(fields=['timestamp'], name='supply_orde_timesta_6a97bb_idx'),
        ),
    ]
